// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Product struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Price       float64     `json:"price"`
	Quantity    int         `json:"quantity"`
	Collection  *Collection `json:"collection"`
}
